site_name: go-proxmox
site_url: https://go-proxmox.iolave.com/
repo_url: https://github.com/iolave/go-proxmox
repo_name: iolave/go-proxmox
plugins:
  - render_swagger
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - github-callouts
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme: 
  name: material
  font: 
    text: Open Sans 
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    #- navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking
    #- search.highlight
    #- search.share
    - search.suggest
    - toc.follow
  icon:
    logo: material/api
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for dark mode
    scheme: default
    primary: deep orange
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
  - Home:
    - index.md
  - Go client:
    - go-client/index.md
    - Reference:
      - pkg:
        - go-client/pkg/cloudflare.md
        - go-client/pkg/helpers.md
        - go-client/pkg/pve.md
        - go-client/pkg/errors.md
    - Implemented endpoints: go-client/implemented-endpoints.md
  - API Wrapper:
    - api-wrapper/index.md
    - api-wrapper/reference.md
  - Changelog: changelog.md
